"use client"

import type { Metadata } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router  = useRouter()
  const oncklickUrl = (url:string) => {
    router.push(url)
  }
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <ul>
          <li><Link href="/"> Home </Link></li>
          <li><Link href="/dashboard">Dashboard </Link></li>
          <li className="btn btn-blue" onClick={() => oncklickUrl("/settings")}>Settings</li>
          <li><Link href="/search">Cari Orang </Link></li>
        </ul>
        {children}
        <div>Footer</div>
      </body>
    </html>
  );
}
