"use client"

import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from 'next/font/google'
import { useRouter } from "next/navigation";
import './ui/globals.css'


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router  = useRouter()
  const oncklickUrl = (url:string) => {
    router.push(url)
  }
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
